services:
  lisp-expert:
    build:
      context: ..
      dockerfile: exp/Dockerfile
    container_name: lisp-expert
    volumes:
      - ..:/app
    ports:
      - "8001:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SBCL_PATH=sbcl

  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: lisp-expert-ui
    ports:
      - "5173:80"
    depends_on:
      - lisp-expert
