services:
  python-expert:
    build: .
    container_name: python-expert
    volumes:
      - .:/app
    command: sh -c "cd src && python main.py"
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
