services:
  python-expert:
    build: .
    container_name: python-expert
    volumes:
      - ..:/app
    command: sh -c "cd src && uvicorn main:app --host 0.0.0.0 --port 8000"
    working_dir: /app/exp
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
